version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432"
  nordismvault:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/nordismvault
    ports:
      - "8000:8000"
    depends_on:
      - db