# Generated by Django 3.1.6 on 2021-02-08 17:59

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('image', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/resources'), upload_to='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('resource', models.ManyToManyField(related_name='tags', to='core.Resource')),
            ],
        ),
    ]
