# Generated by Django 3.1.6 on 2021-02-08 18:29

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/resources'), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.image'),
        ),
    ]
