# Generated by Django 3.1.6 on 2021-02-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210208_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetag',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='core.ResourceTag'),
        ),
    ]
