# Generated by Django 3.1.6 on 2021-02-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='code',
            new_name='drive_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
