# Generated by Django 3.1.7 on 2021-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210319_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='apievent',
            name='action',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
